name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please add screenshots or code/bash samples if applicable.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect to happen?
      description: Please add screenshots or code/bash samples if applicable.
      placeholder: Tell us what you want!
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Use command (version >= 0.8)
        ```bash 
        python3 -m radtools --info 
        ``` 
        or (version < 0.8)
        ```bash
        python3 -c "exec('from radtools import __version__\nprint(__version__)')" 
        ```
        in your terminal to check the version and commit hash of RAD-tools.
  - type: input
    id: version
    attributes:
      label: RAD-tools version
      description: What version of our software are you running?
      placeholder: ex. 0.8.0
    validations:
      required: true
  - type: input
    id: commit
    attributes:
      label: Git commit hash
      description: What commit is the base for the release?
      placeholder: only for versions >= 0.8
    validations:
      required: false
  - type: input
    id: python-version
    attributes:
      label: Python version
      description: What version of Python areyou using our software with?
      placeholder: ex. 3.11.4
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What operating system are you using?
      options:
        - MacOS 
        - Linux 
        - Windows
    validations:
      required: true
  - type: input
    id: OS-info
    attributes:
      label: Additional info about OS
      description: Any information you ant to specify about your OS.
      placeholder: ex. Ubuntu
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Additional informnation
      description: Any additional information you want to add.
    validations:
      required: false
