name: Test dev branch

on:
  pull_request:
    branches: [ dev ]

jobs:
  test-39:
    uses: adrybakov/rad-tools/.github/workflows/run-tests.yml@stable
    with:
      python-version: '3.9'

  test-310:
    uses: adrybakov/rad-tools/.github/workflows/run-tests.yml@stable
    with:
      python-version: '3.10'

  test-311:
    uses: adrybakov/rad-tools/.github/workflows/run-tests.yml@stable
    with:
      python-version: '3.11'

  test-312:
    uses: adrybakov/rad-tools/.github/workflows/run-tests.yml@stable
    with:
      python-version: '3.12'

  test-313:
    uses: adrybakov/rad-tools/.github/workflows/run-tests.yml@stable
    with:
      python-version: '3.13'