name: Test stable branch

on:
  push:
    tags-ignore:
      - '*'
    branches: 
      - 'stable'
  pull_request:
    branches: [ stable ]

jobs:
  test-39:
    name: (3.9) test
    uses: adrybakov/rad-tools/.github/workflows/run-tests.yml@stable
    with:
      python-version: '3.9'

  test-310:
    name: (3.10) test
    uses: adrybakov/rad-tools/.github/workflows/run-tests.yml@stable
    with:
      python-version: '3.10'

  test-311:
    name: (3.11) test
    uses: adrybakov/rad-tools/.github/workflows/run-tests.yml@stable
    with:
      python-version: '3.11'

  test-312:
    name: (3.12) test
    uses: adrybakov/rad-tools/.github/workflows/run-tests.yml@stable
    with:
      python-version: '3.12'

  test-313:
    name: (3.13) test
    uses: adrybakov/rad-tools/.github/workflows/run-tests.yml@stable
    with:
      python-version: '3.13'
